// POST /respond  { bridge, bucket, target, heard, firstMiss? } -> { text }
// KasaAI's encouraging spoken reaction, generated by Gemini (PRD 7.4 step 7).
// The client then voices the returned text with the TTS provider.
import { corsHeaders, json, preflight } from '../_shared/cors.ts';
import { respond, BrainInput } from '../_shared/providers.ts';

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return preflight();
  try {
    const body = (await req.json()) as BrainInput;
    if (!body?.bridge || !body?.bucket) {
      return json({ error: 'bridge and bucket required' }, 400);
    }
    const text = await respond(body);
    return json({ text });
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e) }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
